#!/bin/bash
set -euo pipefail

echo "[01-stage] Staging sensor files..."

SENSOR_DIR=/opt/sensor

mkdir -p "$SENSOR_DIR"

# Copy project files uploaded by the file provisioner
cp /tmp/docker-compose.yml "$SENSOR_DIR/docker-compose.yml"
cp -r /tmp/sensors "$SENSOR_DIR/sensors"
cp -r /tmp/vector "$SENSOR_DIR/vector"

# Create placeholder .env — overwritten at runtime by sensor-provision.service
cat > "$SENSOR_DIR/.env" <<'EOF'
# Auto-generated by sensor-provision.service on first boot.
# Do not edit — place sensor-provision.env in this directory and reboot.
INGEST_API_URL=
INGEST_SHARED_SECRET=
CLIENT_SLUG=
CLIENT_NAME=
SENSOR_ID_SSH=cowrie-ssh-01
SENSOR_ID_HTTP=web-01
SENSOR_ID_FTP=ftp-01
SENSOR_ID_MYSQL=mysql-01
SENSOR_ID_PORT=port-01
SENSOR_ID_DIONAEA=dionaea-01
HONEYPOT_IP=
EOF

chown -R root:docker "$SENSOR_DIR"
chmod -R 750 "$SENSOR_DIR"

echo "[01-stage] Pre-building Docker images (this takes a while)..."

cd "$SENSOR_DIR"

# Pull images that don't need building
docker compose pull --ignore-buildable 2>/dev/null || true

# Build custom sensor images
docker compose build --no-cache --parallel

echo "[01-stage] Docker images built and cached."
echo "[01-stage] Done."
