import { buildCompose, type ServiceKey } from "@/lib/sensor-compose-builder"

export function buildScript(
  deployId: string,
  ingestUrl: string,
  secret: string,
  rawBase: string,
  registry: string,
  services: ServiceKey[],
  clientSlug = "",
  clientName = "",
): string {
  const compose = buildCompose(deployId, ingestUrl, secret, services, registry, clientSlug, clientName)
  return SCRIPT_TEMPLATE
    .replaceAll("{{services}}", services.join(", "))
    .replaceAll("{{clientLine}}", clientLine(clientSlug, clientName))
    .replaceAll("{{rawBase}}", rawBase)
    .replaceAll("{{sshPortStep}}", sshPortStep(services))
    .replaceAll("{{configDownloads}}", configDownloadLines(services))
    .replaceAll("{{compose}}", compose)
}

function clientLine(clientSlug: string, clientName: string) {
  return clientSlug ? `# Client: ${clientName || clientSlug} (${clientSlug})` : ""
}

function configDownloadLines(services: ServiceKey[]) {
  return [
    ...cowrieDownloadLines(services),
    `curl -fsSL "$RAW/vector/suricata.toml"            -o suricata.toml`,
    `curl -fsSL "$RAW/vector/falco.toml"               -o falco.toml`,
    `curl -fsSL "$RAW/sensors/falco/falco.yaml"        -o falco.yaml`,
  ].join("\n")
}

function cowrieDownloadLines(services: ServiceKey[]) {
  if (!services.includes("ssh")) return []
  return [
    `curl -fsSL "$RAW/sensors/cowrie/heartbeat.py" -o heartbeat.py`,
    `curl -fsSL "$RAW/sensors/cowrie/cowrie.cfg"   -o cowrie.cfg`,
    `curl -fsSL "$RAW/sensors/cowrie/userdb.txt"   -o userdb.txt`,
    `curl -fsSL "$RAW/vector/cowrie.toml"          -o cowrie.toml`,
  ]
}

function sshPortStep(services: ServiceKey[]) {
  return services.includes("ssh") ? SSH_PORT_STEP : ""
}

const SSH_PORT_STEP = `
# Move real sshd to port 8022 so Cowrie can claim port 22
if ss -tlnp | grep -q ':22 '; then
  echo "==> Moving sshd to port 8022 to free port 22 for Cowrie..."
  sed -i 's/^#*Port .*/Port 8022/' /etc/ssh/sshd_config
  SOCKET_DROP="/etc/systemd/system/ssh.socket.d"
  mkdir -p "$SOCKET_DROP"
  cat > "$SOCKET_DROP/override.conf" << 'EOF'
[Socket]
ListenStream=
ListenStream=8022
EOF
  systemctl daemon-reload
  systemctl restart ssh.socket 2>/dev/null || systemctl restart sshd 2>/dev/null || true
  echo "    sshd is now on port 8022. Reconnect with: ssh <user>@<host> -p 8022"
fi
`

const SCRIPT_TEMPLATE = `#!/usr/bin/env bash
# Honeypot sensor installer - generated by dashboard
# Sensors: {{services}} + Suricata IDS + Falco
{{clientLine}}
# Run as root or with sudo: bash install-sensor.sh
set -euo pipefail

DIR="/opt/honeypot-sensor"
RAW="{{rawBase}}"

echo "==> Honeypot sensor installer ({{services}} + Suricata IDS + Falco)"
{{sshPortStep}}
# Detect the default public-facing network interface for Suricata
SURICATA_INTERFACE=$(ip route 2>/dev/null | grep '^default' | awk '{print $5}' | head -1)
if [ -z "$SURICATA_INTERFACE" ]; then
  SURICATA_INTERFACE="eth0"
fi
echo "==> Suricata will monitor interface: $SURICATA_INTERFACE"
export SURICATA_INTERFACE

if ! command -v docker &>/dev/null; then
  echo "==> Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi

if ! docker compose version &>/dev/null 2>&1; then
  apt-get install -y docker-compose-plugin 2>/dev/null || true
fi

mkdir -p "$DIR"
cd "$DIR"

echo "==> Downloading config files..."
{{configDownloads}}

echo "==> Writing docker-compose.yml..."
cat > docker-compose.yml << 'ENDOFCOMPOSE'
{{compose}}
ENDOFCOMPOSE

echo "==> Pulling images..."
docker compose pull

echo "==> Starting services..."
SURICATA_INTERFACE="$SURICATA_INTERFACE" docker compose up -d

echo ""
echo "Sensor deployed. It will appear in /sensors within 60 seconds."
echo "Suricata IDS is running on interface: $SURICATA_INTERFACE"
`
