#!/bin/bash
# Runs once on first boot. Reads sensor-provision.env, fetches credentials
# from the platform, writes .env, then starts docker compose.
set -euo pipefail

SENSOR_DIR=/opt/sensor
PROVISION_FILE="$SENSOR_DIR/sensor-provision.env"
ENV_FILE="$SENSOR_DIR/.env"
LOG=/var/log/sensor-provision.log

exec >> "$LOG" 2>&1
echo "[$(date -Is)] sensor-provision starting..."

# ── Wait for network ─────────────────────────────────────────────────────────
echo "[$(date -Is)] Waiting for network..."
for i in $(seq 1 30); do
  if curl -sf --max-time 3 https://1.1.1.1 > /dev/null 2>&1; then
    break
  fi
  sleep 2
done

# ── Check provision file ──────────────────────────────────────────────────────
if [ ! -f "$PROVISION_FILE" ]; then
  echo "[$(date -Is)] ERROR: $PROVISION_FILE not found."
  echo "[$(date -Is)] Copy your sensor-provision.env to $PROVISION_FILE and reboot."
  echo ""
  echo "  scp sensor-provision.env admin@<this-vm-ip>:$PROVISION_FILE"
  echo "  sudo reboot"
  exit 1
fi

# shellcheck source=/dev/null
source "$PROVISION_FILE"

if [ -z "${PROVISION_TOKEN:-}" ] || [ -z "${INGEST_API_URL:-}" ]; then
  echo "[$(date -Is)] ERROR: PROVISION_TOKEN and INGEST_API_URL must be set in $PROVISION_FILE"
  exit 1
fi

# ── Fetch config from platform ────────────────────────────────────────────────
echo "[$(date -Is)] Fetching config from $INGEST_API_URL ..."
PROVISION_RESPONSE=$(curl -sf --max-time 15 "$INGEST_API_URL/sensor/provision?token=$PROVISION_TOKEN")
if [ $? -ne 0 ] || [ -z "$PROVISION_RESPONSE" ]; then
  echo "[$(date -Is)] ERROR: Could not reach provision endpoint."
  echo "[$(date -Is)] Check INGEST_API_URL ($INGEST_API_URL) and PROVISION_TOKEN."
  exit 1
fi

# ── Detect public IP ──────────────────────────────────────────────────────────
HONEYPOT_IP=$(curl -sf --max-time 5 https://api.ipify.org || echo "")
echo "[$(date -Is)] Public IP: ${HONEYPOT_IP:-unknown}"

# ── Write .env ────────────────────────────────────────────────────────────────
{
  echo "# Generated by sensor-provision.service on $(date -Is)"
  echo "$PROVISION_RESPONSE"
  echo "INGEST_API_URL=$INGEST_API_URL"
  echo "HONEYPOT_IP=$HONEYPOT_IP"
} > "$ENV_FILE"

echo "[$(date -Is)] Config written to $ENV_FILE"

# ── Start sensors ─────────────────────────────────────────────────────────────
echo "[$(date -Is)] Starting sensor containers..."
cd "$SENSOR_DIR"
docker compose up -d

echo "[$(date -Is)] Sensors started."

# ── Enable sensor.service so docker compose starts on future reboots ──────────
systemctl enable sensor.service

# ── Disable this service — provisioning complete ──────────────────────────────
systemctl disable sensor-provision.service
echo "[$(date -Is)] Provisioning complete. This service will not run again."
