#!/bin/bash
# Runs once on first boot. Reads credentials from OVF properties (VMware guestInfo)
# or sensor-provision.env fallback, fetches config, starts sensors.
set -euo pipefail

SENSOR_DIR=/opt/sensor
PROVISION_FILE="$SENSOR_DIR/sensor-provision.env"
ENV_FILE="$SENSOR_DIR/.env"
LOG=/var/log/sensor-provision.log

exec >> "$LOG" 2>&1
echo "[$(date -Is)] sensor-provision starting..."

# ── Wait for network ─────────────────────────────────────────────────────────
echo "[$(date -Is)] Waiting for network..."
for i in $(seq 1 30); do
  if curl -sf --max-time 3 https://1.1.1.1 > /dev/null 2>&1; then
    break
  fi
  sleep 2
done

# ── Read credentials: OVF properties first, env file as fallback ─────────────
PROVISION_TOKEN=""
INGEST_API_URL=""

# Try VMware OVF environment via vmtoolsd (works on ESXi, Workstation, Fusion)
if command -v vmtoolsd &>/dev/null; then
  echo "[$(date -Is)] Trying OVF properties via vmtoolsd..."
  OVF_ENV=$(vmtoolsd --cmd "info-get guestinfo.ovfenv" 2>/dev/null || true)

  if [ -n "$OVF_ENV" ]; then
    PROVISION_TOKEN=$(echo "$OVF_ENV" | python3 -c "
import sys, xml.etree.ElementTree as ET
root = ET.fromstring(sys.stdin.read())
ns = 'http://schemas.dmtf.org/ovf/environment/1'
for p in root.iter('{%s}Property' % ns):
    if p.get('{%s}key' % ns) == 'PROVISION_TOKEN':
        print(p.get('{%s}value' % ns, ''))
        break
" 2>/dev/null || echo "")

    INGEST_API_URL=$(echo "$OVF_ENV" | python3 -c "
import sys, xml.etree.ElementTree as ET
root = ET.fromstring(sys.stdin.read())
ns = 'http://schemas.dmtf.org/ovf/environment/1'
for p in root.iter('{%s}Property' % ns):
    if p.get('{%s}key' % ns) == 'INGEST_API_URL':
        print(p.get('{%s}value' % ns, ''))
        break
" 2>/dev/null || echo "")

    if [ -n "$PROVISION_TOKEN" ] && [ -n "$INGEST_API_URL" ]; then
      echo "[$(date -Is)] Credentials read from OVF properties."
    else
      echo "[$(date -Is)] OVF properties found but PROVISION_TOKEN/INGEST_API_URL are empty."
    fi
  else
    echo "[$(date -Is)] No OVF environment data available."
  fi
fi

# Fallback: read from sensor-provision.env file
if [ -z "$PROVISION_TOKEN" ] || [ -z "$INGEST_API_URL" ]; then
  if [ -f "$PROVISION_FILE" ]; then
    echo "[$(date -Is)] Reading credentials from $PROVISION_FILE ..."
    # shellcheck source=/dev/null
    source "$PROVISION_FILE"
  fi
fi

if [ -z "${PROVISION_TOKEN:-}" ] || [ -z "${INGEST_API_URL:-}" ]; then
  echo "[$(date -Is)] ERROR: PROVISION_TOKEN and INGEST_API_URL not found."
  echo "[$(date -Is)] Either the OVA was not generated with embedded credentials,"
  echo "[$(date -Is)] or $PROVISION_FILE is missing."
  echo "[$(date -Is)] Place the file and reboot:"
  echo "  scp sensor-provision.env sensor@<this-vm-ip>:$PROVISION_FILE"
  echo "  sudo reboot"
  exit 1
fi

# ── Fetch config from platform ────────────────────────────────────────────────
echo "[$(date -Is)] Fetching config from $INGEST_API_URL ..."
PROVISION_RESPONSE=$(curl -sf --max-time 15 "$INGEST_API_URL/sensor/provision?token=$PROVISION_TOKEN")
if [ $? -ne 0 ] || [ -z "$PROVISION_RESPONSE" ]; then
  echo "[$(date -Is)] ERROR: Could not reach provision endpoint."
  echo "[$(date -Is)] Check INGEST_API_URL ($INGEST_API_URL) and PROVISION_TOKEN."
  exit 1
fi

# ── Detect public IP ──────────────────────────────────────────────────────────
HONEYPOT_IP=$(curl -sf --max-time 5 https://api.ipify.org || echo "")
echo "[$(date -Is)] Public IP: ${HONEYPOT_IP:-unknown}"

# ── Write .env ────────────────────────────────────────────────────────────────
{
  echo "# Generated by sensor-provision.service on $(date -Is)"
  echo "$PROVISION_RESPONSE"
  echo "INGEST_API_URL=$INGEST_API_URL"
  echo "HONEYPOT_IP=$HONEYPOT_IP"
} > "$ENV_FILE"

echo "[$(date -Is)] Config written to $ENV_FILE"

# ── Start sensors ─────────────────────────────────────────────────────────────
echo "[$(date -Is)] Starting sensor containers..."
cd "$SENSOR_DIR"

if [ -n "${ENABLED_COMPOSE_SERVICES:-}" ]; then
  echo "[$(date -Is)] Enabled services: $ENABLED_COMPOSE_SERVICES"
  # shellcheck disable=SC2086
  docker compose up -d $ENABLED_COMPOSE_SERVICES
else
  docker compose up -d
fi

echo "[$(date -Is)] Sensors started."

# ── Enable sensor.service so docker compose starts on future reboots ──────────
systemctl enable sensor.service

# ── Disable this service — provisioning complete ──────────────────────────────
systemctl disable sensor-provision.service
echo "[$(date -Is)] Provisioning complete. This service will not run again."
