import { NextResponse } from "next/server"
import type { NextRequest } from "next/server"
import { logAudit } from "@/lib/audit"
import { requireRole } from "@/lib/roles"

async function resolveIngestUrl(): Promise<string | null> {
  if (process.env.SENSOR_INGEST_URL) return process.env.SENSOR_INGEST_URL

  const configured = process.env.NEXT_PUBLIC_API_URL ?? ""
  if (configured && !configured.includes("localhost") && !configured.includes("127.0.0.1")) {
    return configured
  }

  try {
    const res = await fetch("https://api.ipify.org?format=text", {
      signal: AbortSignal.timeout(5000),
    })
    if (!res.ok) throw new Error("ipify error")
    return `http://${(await res.text()).trim()}:3000`
  } catch {
    return null
  }
}

function buildCompose(ingestUrl: string, secret: string): string {
  return `# Generated by Honeypot Platform dashboard
# Run with: docker compose -f docker-compose.sensor.yml up -d
# (requires the repo to be cloned on this machine)
#
# Set SURICATA_INTERFACE to your public network interface before starting:
#   export SURICATA_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -1)
#   docker compose -f docker-compose.sensor.yml up -d

x-service-defaults: &service-defaults
  restart: unless-stopped
  init: true
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL

x-json-logging: &json-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-ingest-env: &ingest-env
  INGEST_API_URL: "${ingestUrl}"
  INGEST_SHARED_SECRET: "${secret}"

services:
  cowrie:
    <<: *service-defaults
    logging: *json-logging
    build:
      context: ./sensors/cowrie
    container_name: cowrie
    ports:
      - "22:2222"
      - "2222:2222"
    volumes:
      - cowrie_var:/cowrie/cowrie-git/var
      - ./sensors/cowrie/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
      - ./sensors/cowrie/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt:ro
    networks:
      - edge
    pids_limit: 256

  cowrie-beacon:
    <<: *service-defaults
    logging: *json-logging
    image: python:3.12-alpine
    container_name: cowrie-beacon
    environment:
      <<: *ingest-env
      SENSOR_ID: cowrie-ssh-01
      SENSOR_NAME: SSH Honeypot (Cowrie)
      SENSOR_IP: ""
      SENSOR_PROTOCOL: ssh
      SENSOR_VERSION: cowrie
      SENSOR_PORTS: "22 2222"
      SENSOR_PROBE_PORTS: "2222 2222"
      SENSOR_HOST: cowrie
    volumes:
      - ./sensors/cowrie/heartbeat.py:/heartbeat.py:ro
    command: ["python3", "/heartbeat.py"]
    networks:
      - edge
    pids_limit: 16

  web-honeypot:
    <<: *service-defaults
    logging: *json-logging
    build:
      context: ./sensors/web-honeypot
    container_name: web-honeypot
    environment:
      <<: *ingest-env
      PORT: "8080"
      SENSOR_ID: web-01
      SENSOR_NAME: Web Honeypot
      SENSOR_IP: ""
      SENSOR_HOST: web-honeypot
      SENSOR_PORTS: "80 8443"
      SENSOR_PROBE_PORTS: "8080 8080"
    ports:
      - "80:8080"
      - "8443:8080"
    read_only: true
    networks:
      - edge
    tmpfs:
      - /tmp
    pids_limit: 128

  suricata:
    logging: *json-logging
    build:
      context: ./sensors/suricata
    container_name: suricata
    restart: unless-stopped
    init: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
      - SETPCAP
      - SETUID
      - SETGID
    environment:
      SURICATA_INTERFACE: \${SURICATA_INTERFACE:-eth0}
    volumes:
      - suricata_logs:/tmp/suricata-logs
    pids_limit: 256

  falco:
    image: falcosecurity/falco-no-driver:latest
    container_name: falco
    restart: unless-stopped
    init: true
    pid: host
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./sensors/falco/falco.yaml:/etc/falco/falco.yaml:ro
      - falco_logs:/var/log/falco
    pids_limit: 128

  vector:
    <<: *service-defaults
    logging: *json-logging
    image: timberio/vector:0.40.0-alpine
    container_name: vector
    depends_on:
      - cowrie
    volumes:
      - cowrie_var:/cowrie/cowrie-git/var:ro
      - suricata_logs:/tmp/suricata-logs:ro
      - falco_logs:/var/log/falco:ro
      - ./vector/cowrie.toml:/etc/vector/cowrie.toml:ro
      - ./vector/suricata.toml:/etc/vector/suricata.toml:ro
      - ./vector/falco.toml:/etc/vector/falco.toml:ro
      - vector_data:/var/lib/vector
    command: ["--config", "/etc/vector/cowrie.toml", "--config", "/etc/vector/suricata.toml", "--config", "/etc/vector/falco.toml"]
    environment:
      <<: *ingest-env
      COWRIE_LOG_PATH: /cowrie/cowrie-git/var/log/cowrie/cowrie.json
      SENSOR_ID: cowrie-ssh-01
      SURICATA_SENSOR_ID: suricata-01
      FALCO_SENSOR_ID: falco-01
    networks:
      - edge
    pids_limit: 128

  ftp-honeypot:
    <<: *service-defaults
    logging: *json-logging
    build:
      context: ./sensors/ftp-honeypot
    container_name: ftp-honeypot
    environment:
      <<: *ingest-env
      PORT: "21"
      DST_PORT: "21"
      SENSOR_ID: ftp-01
      SENSOR_NAME: FTP Honeypot
      SENSOR_IP: ""
    ports:
      - "21:21"
    networks:
      - edge
    pids_limit: 128

  mysql-honeypot:
    <<: *service-defaults
    logging: *json-logging
    build:
      context: ./sensors/mysql-honeypot
    container_name: mysql-honeypot
    environment:
      <<: *ingest-env
      PORT: "3306"
      DST_PORT: "3306"
      SENSOR_ID: mysql-01
      SENSOR_NAME: MySQL Honeypot
      SENSOR_IP: ""
    ports:
      - "3306:3306"
    networks:
      - edge
    pids_limit: 128

  port-honeypot:
    <<: *service-defaults
    logging: *json-logging
    build:
      context: ./sensors/port-honeypot
    container_name: port-honeypot
    environment:
      <<: *ingest-env
      PORTS: "1433 2375 3389 4444 5900 6379 8888 9090 9200 27017"
      SENSOR_ID: port-01
      SENSOR_NAME: Port Honeypot
      SENSOR_IP: ""
    ports:
      - "1433:1433"
      - "2375:2375"
      - "3389:3389"
      - "4444:4444"
      - "5900:5900"
      - "6379:6379"
      - "8888:8888"
      - "9090:9090"
      - "9200:9200"
      - "27017:27017"
    networks:
      - edge
    pids_limit: 256

volumes:
  cowrie_var:
  vector_data:
  suricata_logs:
  falco_logs:

networks:
  edge:
    driver: bridge
`
}

export async function GET(req: NextRequest) {
  const auth_check = await requireRole("analyst")
  if (!auth_check.ok) return auth_check.response

  const ingestUrl = await resolveIngestUrl()
  if (!ingestUrl) {
    return NextResponse.json(
      { error: "Could not resolve ingest URL. Set SENSOR_INGEST_URL in your .env" },
      { status: 500 },
    )
  }

  const secret = process.env.INGEST_SHARED_SECRET ?? ""
  if (!secret) {
    return NextResponse.json({ error: "INGEST_SHARED_SECRET is not set" }, { status: 500 })
  }

  await logAudit({
    action: "DOWNLOAD",
    resource: "SENSOR",
    resourceName: "docker-compose.sensor.yml",
    details: { filename: "docker-compose.sensor.yml" },
    request: req,
  })

  return new NextResponse(buildCompose(ingestUrl, secret), {
    headers: {
      "Content-Type": "text/yaml; charset=utf-8",
      "Content-Disposition": 'attachment; filename="docker-compose.sensor.yml"',
    },
  })
}
