import { NextResponse } from "next/server"
import type { NextRequest } from "next/server"
import { logAudit } from "@/lib/audit"
import { requireRole } from "@/lib/roles"
import { buildCompose, genDeployId } from "@/lib/sensor-compose-builder"

const RAW_BASE = process.env.SENSOR_RAW_BASE ?? "https://raw.githubusercontent.com/elrichi31/honeypot-ai/master"

async function resolveIngestUrl(): Promise<string | null> {
  if (process.env.SENSOR_INGEST_URL) return process.env.SENSOR_INGEST_URL
  const configured = process.env.NEXT_PUBLIC_API_URL ?? ""
  if (configured && !configured.includes("localhost") && !configured.includes("127.0.0.1")) return configured
  try {
    const res = await fetch("https://api.ipify.org?format=text", { signal: AbortSignal.timeout(5000) })
    if (!res.ok) throw new Error("ipify error")
    return `http://${(await res.text()).trim()}:3000`
  } catch {
    return null
  }
}

function missingConfigResponse(ingestUrl: string | null, secret: string) {
  if (!ingestUrl) {
    return NextResponse.json(
      { error: "Could not resolve ingest URL. Set SENSOR_INGEST_URL in your .env" },
      { status: 500 },
    )
  }
  return secret ? null : NextResponse.json({ error: "INGEST_SHARED_SECRET is not set" }, { status: 500 })
}

function composeDownload(deployId: string, ingestUrl: string, secret: string) {
  return `${composeInstructions(deployId)}\n\n${buildCompose(deployId, ingestUrl, secret)}\n`
}

function composeInstructions(deployId: string) {
  return `# Generated by Honeypot Platform dashboard
# Deploy ID: ${deployId}
#
# Usage:
#   1. Download config files into this directory:
#        RAW=${RAW_BASE}
#        curl -fsSL "$RAW/sensors/cowrie/heartbeat.py" -o heartbeat.py
#        curl -fsSL "$RAW/sensors/cowrie/cowrie.cfg"   -o cowrie.cfg
#        curl -fsSL "$RAW/sensors/cowrie/userdb.txt"   -o userdb.txt
#        curl -fsSL "$RAW/vector/cowrie.toml"          -o cowrie.toml
#        curl -fsSL "$RAW/vector/suricata.toml"        -o suricata.toml
#
#   2. Set SURICATA_INTERFACE to your public-facing network interface:
#        export SURICATA_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -1)
#
#   3. Start:
#        SURICATA_INTERFACE=$SURICATA_INTERFACE docker compose -f docker-compose.sensor.yml up -d
#
# Tip: use the install script (Dashboard -> Sensors -> Download install.sh) for a one-command setup.`
}

export async function GET(req: NextRequest) {
  const authCheck = await requireRole("analyst")
  if (!authCheck.ok) return authCheck.response

  const ingestUrl = await resolveIngestUrl()
  const secret = process.env.INGEST_SHARED_SECRET ?? ""
  const configError = missingConfigResponse(ingestUrl, secret)
  if (configError) return configError
  if (!ingestUrl) return NextResponse.json({ error: "Could not resolve ingest URL" }, { status: 500 })

  const deployId = genDeployId()
  await logComposeDownload(req, deployId)
  return new NextResponse(composeDownload(deployId, ingestUrl, secret), {
    headers: {
      "Content-Type": "text/yaml; charset=utf-8",
      "Content-Disposition": 'attachment; filename="docker-compose.sensor.yml"',
    },
  })
}

async function logComposeDownload(req: NextRequest, deployId: string) {
  await logAudit({
    action: "DOWNLOAD",
    resource: "SENSOR",
    resourceName: "docker-compose.sensor.yml",
    details: { filename: "docker-compose.sensor.yml", deployId },
    request: req,
  })
}
